/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as TeacherGamesRouteImport } from './routes/teacher.games'
import { Route as PlayVideoIdRouteImport } from './routes/play.$videoId'
import { Route as GamesQuizRouteImport } from './routes/games.quiz'
import { Route as GamesMemoryRouteImport } from './routes/games.memory'
import { Route as GamesLabelRouteImport } from './routes/games.label'
import { Route as GamesJigsawRouteImport } from './routes/games.jigsaw'
import { Route as TeacherVideoVideoIdRouteImport } from './routes/teacher.video.$videoId'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherGamesRoute = TeacherGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => TeacherRoute,
} as any)
const PlayVideoIdRoute = PlayVideoIdRouteImport.update({
  id: '/play/$videoId',
  path: '/play/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesQuizRoute = GamesQuizRouteImport.update({
  id: '/games/quiz',
  path: '/games/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMemoryRoute = GamesMemoryRouteImport.update({
  id: '/games/memory',
  path: '/games/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesLabelRoute = GamesLabelRouteImport.update({
  id: '/games/label',
  path: '/games/label',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesJigsawRoute = GamesJigsawRouteImport.update({
  id: '/games/jigsaw',
  path: '/games/jigsaw',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherVideoVideoIdRoute = TeacherVideoVideoIdRouteImport.update({
  id: '/video/$videoId',
  path: '/video/$videoId',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matching': typeof MatchingRoute
  '/scan': typeof ScanRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/games/jigsaw': typeof GamesJigsawRoute
  '/games/label': typeof GamesLabelRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/quiz': typeof GamesQuizRoute
  '/play/$videoId': typeof PlayVideoIdRoute
  '/teacher/games': typeof TeacherGamesRoute
  '/games/': typeof GamesIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/video/$videoId': typeof TeacherVideoVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matching': typeof MatchingRoute
  '/scan': typeof ScanRoute
  '/student': typeof StudentRoute
  '/games/jigsaw': typeof GamesJigsawRoute
  '/games/label': typeof GamesLabelRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/quiz': typeof GamesQuizRoute
  '/play/$videoId': typeof PlayVideoIdRoute
  '/teacher/games': typeof TeacherGamesRoute
  '/games': typeof GamesIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/teacher/video/$videoId': typeof TeacherVideoVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matching': typeof MatchingRoute
  '/scan': typeof ScanRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/games/jigsaw': typeof GamesJigsawRoute
  '/games/label': typeof GamesLabelRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/quiz': typeof GamesQuizRoute
  '/play/$videoId': typeof PlayVideoIdRoute
  '/teacher/games': typeof TeacherGamesRoute
  '/games/': typeof GamesIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/video/$videoId': typeof TeacherVideoVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/matching'
    | '/scan'
    | '/student'
    | '/teacher'
    | '/games/jigsaw'
    | '/games/label'
    | '/games/memory'
    | '/games/quiz'
    | '/play/$videoId'
    | '/teacher/games'
    | '/games/'
    | '/teacher/'
    | '/teacher/video/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/matching'
    | '/scan'
    | '/student'
    | '/games/jigsaw'
    | '/games/label'
    | '/games/memory'
    | '/games/quiz'
    | '/play/$videoId'
    | '/teacher/games'
    | '/games'
    | '/teacher'
    | '/teacher/video/$videoId'
  id:
    | '__root__'
    | '/'
    | '/matching'
    | '/scan'
    | '/student'
    | '/teacher'
    | '/games/jigsaw'
    | '/games/label'
    | '/games/memory'
    | '/games/quiz'
    | '/play/$videoId'
    | '/teacher/games'
    | '/games/'
    | '/teacher/'
    | '/teacher/video/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchingRoute: typeof MatchingRoute
  ScanRoute: typeof ScanRoute
  StudentRoute: typeof StudentRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  GamesJigsawRoute: typeof GamesJigsawRoute
  GamesLabelRoute: typeof GamesLabelRoute
  GamesMemoryRoute: typeof GamesMemoryRoute
  GamesQuizRoute: typeof GamesQuizRoute
  PlayVideoIdRoute: typeof PlayVideoIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/games': {
      id: '/teacher/games'
      path: '/games'
      fullPath: '/teacher/games'
      preLoaderRoute: typeof TeacherGamesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/play/$videoId': {
      id: '/play/$videoId'
      path: '/play/$videoId'
      fullPath: '/play/$videoId'
      preLoaderRoute: typeof PlayVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/quiz': {
      id: '/games/quiz'
      path: '/games/quiz'
      fullPath: '/games/quiz'
      preLoaderRoute: typeof GamesQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/memory': {
      id: '/games/memory'
      path: '/games/memory'
      fullPath: '/games/memory'
      preLoaderRoute: typeof GamesMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/label': {
      id: '/games/label'
      path: '/games/label'
      fullPath: '/games/label'
      preLoaderRoute: typeof GamesLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/jigsaw': {
      id: '/games/jigsaw'
      path: '/games/jigsaw'
      fullPath: '/games/jigsaw'
      preLoaderRoute: typeof GamesJigsawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/video/$videoId': {
      id: '/teacher/video/$videoId'
      path: '/video/$videoId'
      fullPath: '/teacher/video/$videoId'
      preLoaderRoute: typeof TeacherVideoVideoIdRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface TeacherRouteChildren {
  TeacherGamesRoute: typeof TeacherGamesRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherVideoVideoIdRoute: typeof TeacherVideoVideoIdRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherGamesRoute: TeacherGamesRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherVideoVideoIdRoute: TeacherVideoVideoIdRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchingRoute: MatchingRoute,
  ScanRoute: ScanRoute,
  StudentRoute: StudentRoute,
  TeacherRoute: TeacherRouteWithChildren,
  GamesJigsawRoute: GamesJigsawRoute,
  GamesLabelRoute: GamesLabelRoute,
  GamesMemoryRoute: GamesMemoryRoute,
  GamesQuizRoute: GamesQuizRoute,
  PlayVideoIdRoute: PlayVideoIdRoute,
  GamesIndexRoute: GamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
